quiz.js doesn't contain: ["checkAnswer"]
quiz.js doesn't contain: ["correctAnswer", "4"]
quiz.js doesn't contain: ["document.querySelector", "checked", "value"] / quiz.js doesn't contain: ["userAnswer"]
quiz.js doesn't contain: ["if (userAnswer === correctAnswer)"]
quiz.js doesn't contain: ["document.querySelector("] / quiz.js doesn't contain: ["Correct! Well done."]
quiz.js doesn't contain: ["That's incorrect. Try again!"]
